
language: objective-c
osx_image: xcode10

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:

    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail
    - xcodebuild clean build -project Retriable.xcodeproj -target 'Retriable iOS' -sdk iphonesimulator -configuration Debug | xcpretty
    - xcodebuild clean build -project Retriable.xcodeproj -target 'Retriable watchOS' -sdk watchsimulator -configuration Debug | xcpretty
    - xcodebuild clean build -project Retriable.xcodeproj -target 'Retriable tvOS'  -sdk appletvsimulator -configuration Debug | xcpretty
    - xcodebuild clean build -project Retriable.xcodeproj -target 'Retriable macOS' -sdk macosx -configuration Debug | xcpretty
